# Generated by Django 5.2 on 2025-04-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_average',
            field=models.FloatField(default=0.0),
        ),
    ]
