# Generated by Django 5.2 on 2025-04-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caddie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bib_color', models.CharField(max_length=100)),
            ],
        ),
    ]
