# Generated by Django 5.2 on 2025-04-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTeeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timeslot')),
            ],
        ),
    ]
