# Generated by Django 5.2 on 2025-04-29 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_memberteetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberteetime',
            name='caddie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_caddie', to='app.caddie'),
        ),
    ]
