# Generated by Django 5.2 on 2025-04-30 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_memberteetime_caddie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberteetime',
            name='caddie',
        ),
        migrations.AddField(
            model_name='member',
            name='caddie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.caddie'),
        ),
    ]
