# Generated by Django 5.2 on 2025-05-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_memberteetime_caddie_member_caddie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_course', models.CharField(max_length=100)),
            ],
        ),
    ]
